import type {
  ItemDefinition,
  ItemId,
  RecipeDefinition,
  RecipeId,
  ResourceRegenerationDefinition,
  TaskDefinition,
  TaskId,
  WorldEntityTemplate,
} from "./types";

/**
 * Renewable world resources regrow one unit at deterministic simulation-time
 * intervals. Objective/rare resources are deliberately absent from this map;
 * in particular, the weather-station battery can never regenerate.
 */
export const RESOURCE_REGENERATION: Partial<
  Record<ItemId, ResourceRegenerationDefinition>
> = {
  stone: { intervalSeconds: 480, amount: 1, minimumPlayerDistance: 12 },
  stick: { intervalSeconds: 120, amount: 1, minimumPlayerDistance: 12 },
  vine: { intervalSeconds: 240, amount: 1, minimumPlayerDistance: 12 },
  "broad-leaf": { intervalSeconds: 180, amount: 1, minimumPlayerDistance: 12 },
  "medicinal-leaf": { intervalSeconds: 300, amount: 1, minimumPlayerDistance: 14 },
  "dry-leaf": { intervalSeconds: 240, amount: 1, minimumPlayerDistance: 12 },
  coconut: { intervalSeconds: 360, amount: 1, minimumPlayerDistance: 14 },
  "antiparasitic-herb": { intervalSeconds: 360, amount: 1, minimumPlayerDistance: 14 },
  "palm-fruit": { intervalSeconds: 300, amount: 1, minimumPlayerDistance: 14 },
  "brazil-nuts": { intervalSeconds: 420, amount: 1, minimumPlayerDistance: 14 },
  grubs: { intervalSeconds: 180, amount: 1, minimumPlayerDistance: 12 },
};

export const ITEMS: Record<ItemId, ItemDefinition> = {
  stone: { id: "stone", label: "锋利石块", stackLimit: 24 },
  stick: { id: "stick", label: "木棍", stackLimit: 32 },
  vine: { id: "vine", label: "藤条", stackLimit: 24 },
  "broad-leaf": { id: "broad-leaf", label: "宽叶", stackLimit: 32 },
  "medicinal-leaf": {
    id: "medicinal-leaf",
    label: "药草叶",
    stackLimit: 12,
  },
  "dry-leaf": { id: "dry-leaf", label: "干叶", stackLimit: 20 },
  coconut: { id: "coconut", label: "椰子", stackLimit: 8 },
  "coconut-shell": {
    id: "coconut-shell",
    label: "椰壳容器",
    stackLimit: 8,
  },
  "dirty-water": { id: "dirty-water", label: "浑浊溪水", stackLimit: 8 },
  "clean-water": { id: "clean-water", label: "煮沸净水", stackLimit: 8 },
  "stone-blade": { id: "stone-blade", label: "石刃", stackLimit: 2 },
  axe: { id: "axe", label: "石斧", stackLimit: 2 },
  bandage: { id: "bandage", label: "草药绷带", stackLimit: 8 },
  spear: { id: "spear", label: "石矛", stackLimit: 2 },
  battery: { id: "battery", label: "气象站电池", stackLimit: 1 },
  "antiparasitic-herb": {
    id: "antiparasitic-herb",
    label: "驱虫草药",
    stackLimit: 6,
  },
  "palm-fruit": {
    id: "palm-fruit",
    label: "棕榈果",
    stackLimit: 10,
    edible: { carbohydrates: 24, hydration: 6, energy: 5 },
  },
  "brazil-nuts": {
    id: "brazil-nuts",
    label: "巴西坚果",
    stackLimit: 10,
    edible: { fat: 25, protein: 5, energy: 7 },
  },
  grubs: {
    id: "grubs",
    label: "甲虫幼虫",
    stackLimit: 10,
    edible: { protein: 22, energy: 4, sanity: -3 },
  },
};

export const RECIPES: Record<RecipeId, RecipeDefinition> = {
  "stone-blade": {
    id: "stone-blade",
    label: "打制石刃",
    ingredients: { stone: 2 },
    results: { "stone-blade": 1 },
    workSeconds: 20,
  },
  axe: {
    id: "axe",
    label: "捆扎石斧",
    ingredients: { stone: 2, stick: 1, vine: 1 },
    tools: ["stone-blade"],
    results: { axe: 1 },
    workSeconds: 30,
  },
  bandage: {
    id: "bandage",
    label: "制作草药绷带",
    ingredients: { "medicinal-leaf": 1, vine: 1 },
    results: { bandage: 1 },
    workSeconds: 25,
  },
  "coconut-shell": {
    id: "coconut-shell",
    label: "剖开椰子",
    ingredients: { coconut: 1 },
    tools: ["stone-blade"],
    results: { "coconut-shell": 2 },
    workSeconds: 18,
  },
  campfire: {
    id: "campfire",
    label: "搭建营火",
    ingredients: { stick: 4, "dry-leaf": 2 },
    effect: "build-fire",
    requiresCamp: true,
    workSeconds: 45,
  },
  shelter: {
    id: "shelter",
    label: "搭建叶棚",
    ingredients: { stick: 6, vine: 4, "broad-leaf": 4 },
    tools: ["axe"],
    effect: "build-shelter",
    requiresCamp: true,
    workSeconds: 90,
  },
  bed: {
    id: "bed",
    label: "铺设棕榈床",
    ingredients: { stick: 4, vine: 2, "broad-leaf": 6 },
    tools: ["axe"],
    effect: "build-bed",
    requiresCamp: true,
    workSeconds: 65,
  },
  spear: {
    id: "spear",
    label: "削制石矛",
    ingredients: { stick: 2, vine: 1 },
    tools: ["stone-blade"],
    results: { spear: 1 },
    workSeconds: 30,
  },
  "radio-beacon": {
    id: "radio-beacon",
    label: "修复求救信标",
    ingredients: { battery: 1, stick: 1, vine: 1 },
    tools: ["stone-blade"],
    effect: "build-beacon",
    requiresCamp: true,
    workSeconds: 50,
  },
};

export const TASK_SEQUENCE: readonly TaskId[] = [
  "treat-wound",
  "purify-water",
  "establish-camp",
  "recover-battery",
  "transmit-signal",
];

export const TASKS: Record<TaskId, TaskDefinition> = {
  "treat-wound": {
    id: "treat-wound",
    label: "先止住血",
    description: "检查伤口，观察坠落点附近能黏合、捆扎的植物。",
    flag: "woundTreated",
  },
  "purify-water": {
    id: "purify-water",
    label: "确认安全补水",
    description: "找到水源，判断污染风险，并真正喝下一份安全饮水。",
    flag: "waterPurified",
  },
  "establish-camp": {
    id: "establish-camp",
    label: "建立过夜营地",
    description: "让坠落点具备过夜所需的火、遮蔽与离地休息处。",
    flag: "campEstablished",
  },
  "recover-battery": {
    id: "recover-battery",
    label: "前往气象站",
    description: "沿山脊找到废弃气象站并取回电池。",
    flag: "batteryRecovered",
  },
  "transmit-signal": {
    id: "transmit-signal",
    label: "回营发出求救信号",
    description: "把电池带回营地，修复信标并发报。",
    flag: "transmitted",
  },
};

export const WORLD_ENTITY_TEMPLATES: readonly WorldEntityTemplate[] = [
  {
    id: "landmark.camp-radio",
    kind: "radio",
    label: "损坏的营地电台",
    position: { x: 0, y: 0, z: 0 },
    interactRadius: 3,
    quantity: 1,
    tags: ["camp", "objective"],
  },
  {
    id: "landmark.stream",
    kind: "water",
    label: "浑浊溪流",
    position: { x: 12, y: 0, z: -14 },
    interactRadius: 3.5,
    quantity: 1,
    contamination: 0.62,
    tags: ["water", "landmark"],
  },
  {
    id: "landmark.weather-station",
    kind: "landmark",
    label: "废弃气象站",
    position: { x: 33, y: 0, z: 27 },
    interactRadius: 5,
    quantity: 1,
    tags: ["objective", "landmark"],
  },
  {
    id: "landmark.survey-cache",
    kind: "landmark",
    label: "岩棚里的勘测箱",
    position: { x: -35, y: 0, z: 31 },
    interactRadius: 3,
    quantity: 1,
    tags: ["objective", "landmark", "clue", "cache"],
  },
  {
    id: "resource.battery.weather-station",
    kind: "resource",
    label: "气象站电池",
    position: { x: 32, y: 0, z: 25 },
    interactRadius: 2.5,
    itemId: "battery",
    quantity: 1,
    tags: ["objective", "rare"],
  },
  {
    id: "hazard.snake.stream-ridge",
    kind: "hazard",
    label: "眼镜蛇",
    position: { x: 18, y: 0, z: -5 },
    interactRadius: 3,
    quantity: 1,
    tags: ["animal", "threat", "audible"],
  },
  {
    id: "hazard.snake.station-trail",
    kind: "hazard",
    label: "灌木中的眼镜蛇",
    position: { x: 27, y: 0, z: 18 },
    interactRadius: 3,
    quantity: 1,
    tags: ["animal", "threat", "audible"],
  },
  {
    id: "resource.stone.camp-01",
    kind: "resource",
    label: "河滩石堆",
    position: { x: 3, y: 0, z: 2 },
    interactRadius: 2.5,
    itemId: "stone",
    quantity: 4,
    tags: ["camp", "crafting"],
  },
  {
    id: "resource.stick.camp-01",
    kind: "resource",
    label: "风折木堆",
    position: { x: -3, y: 0, z: 1 },
    interactRadius: 2.5,
    itemId: "stick",
    quantity: 10,
    tags: ["camp", "crafting"],
  },
  {
    id: "resource.vine.camp-01",
    kind: "resource",
    label: "垂落藤蔓",
    position: { x: -2, y: 0, z: 4 },
    interactRadius: 2.5,
    itemId: "vine",
    quantity: 6,
    tags: ["camp", "crafting"],
  },
  {
    id: "resource.leaf.camp-01",
    kind: "resource",
    label: "宽叶棕榈",
    position: { x: 4, y: 0, z: -3 },
    interactRadius: 2.5,
    itemId: "broad-leaf",
    quantity: 12,
    tags: ["camp", "crafting"],
  },
  {
    id: "resource.medicinal.camp-01",
    kind: "resource",
    label: "船子草",
    position: { x: 2, y: 0, z: -4 },
    interactRadius: 2.5,
    itemId: "medicinal-leaf",
    quantity: 2,
    tags: ["camp", "medicine"],
  },
  {
    id: "resource.dry-leaf.camp-01",
    kind: "resource",
    label: "岩缝干叶",
    position: { x: -4, y: 0, z: -2 },
    interactRadius: 2.5,
    itemId: "dry-leaf",
    quantity: 5,
    tags: ["camp", "tinder"],
  },
  {
    id: "resource.coconut.stream-01",
    kind: "resource",
    label: "落地椰子",
    position: { x: 10, y: 0, z: -12 },
    interactRadius: 2.5,
    itemId: "coconut",
    quantity: 3,
    tags: ["water", "container"],
  },
  {
    id: "resource.stick.trail-01",
    kind: "resource",
    label: "倒伏枯枝",
    position: { x: 18, y: 1, z: 14 },
    interactRadius: 2.5,
    itemId: "stick",
    quantity: 12,
    tags: ["trail", "crafting"],
  },
  {
    id: "resource.vine.trail-01",
    kind: "resource",
    label: "老藤",
    position: { x: 21, y: 1, z: 16 },
    interactRadius: 2.5,
    itemId: "vine",
    quantity: 8,
    tags: ["trail", "crafting"],
  },
  {
    id: "resource.leaf.trail-01",
    kind: "resource",
    label: "棕榈叶簇",
    position: { x: 24, y: 2, z: 18 },
    interactRadius: 2.5,
    itemId: "broad-leaf",
    quantity: 10,
    tags: ["trail", "crafting"],
  },
  {
    id: "resource.stone.trail-01",
    kind: "resource",
    label: "裸露碎石",
    position: { x: 28, y: 2, z: 22 },
    interactRadius: 2.5,
    itemId: "stone",
    quantity: 5,
    tags: ["trail", "crafting"],
  },
  {
    id: "resource.dry-leaf.trail-01",
    kind: "resource",
    label: "棚屋残骸中的干叶",
    position: { x: 31, y: 3, z: 25 },
    interactRadius: 2.5,
    itemId: "dry-leaf",
    quantity: 4,
    tags: ["trail", "tinder"],
  },
  {
    id: "resource.antiparasitic.stream-01",
    kind: "resource",
    label: "苦味驱虫草",
    position: { x: 14, y: 0, z: -11 },
    interactRadius: 2.5,
    itemId: "antiparasitic-herb",
    quantity: 2,
    tags: ["water", "medicine"],
  },
  {
    id: "resource.fruit.camp-01",
    kind: "resource",
    label: "棕榈果串",
    position: { x: -5, y: 0, z: 5 },
    interactRadius: 2.5,
    itemId: "palm-fruit",
    quantity: 5,
    tags: ["camp", "food"],
  },
  {
    id: "resource.nuts.trail-01",
    kind: "resource",
    label: "巴西坚果",
    position: { x: 20, y: 1, z: 12 },
    interactRadius: 2.5,
    itemId: "brazil-nuts",
    quantity: 4,
    tags: ["trail", "food"],
  },
  {
    id: "resource.grubs.log-01",
    kind: "resource",
    label: "腐木中的幼虫",
    position: { x: 8, y: 0, z: -6 },
    interactRadius: 2.5,
    itemId: "grubs",
    quantity: 4,
    tags: ["camp", "food"],
  },
];
